### ISSUE TITLE
Undefined index: timeInSeconds

### ISSUE THREAD

**Issue by CarstenHager** [lochmueller/seocli#1]
Hey Tim,

wenn der Crawler bei mir läuft, werden mir folgende Hinweise im PHP-ErrorLog ausgegeben.
Pro Seite die aufgerufen wird ein Hinweis.

[12-Oct-2018 07:31:19 Europe/Berlin] PHP Notice:  Undefined index: timeInSeconds in /html/helper/seocli/src/Application.php on line 105

**Comment by lochmueller** [comment]
Hey @CarstenHager Fehler gefunden und korrigiert. War ein Rechtschreibfehler im Exception Handling der Request Klasse. Danke fürs melden. Grüße, Tim
