### ISSUE TITLE
[FEATURE] output to file

### ISSUE THREAD

**Issue by Patta** [lochmueller/seocli#2]
It would be nice if there is an option, that writes the output and errors in a log file.
Use case: seocli is running via cron job.

**Comment by lochmueller** [comment]
Hey @Patta 
What should apear in this file? The same output of the command itself?
Perhaps a simple `>` do the magic you need? 
`./bin/seocli -u https://www.website.de -d 1 -f csv > logfile.csv`

Please send me some feedback.

Regards,
Tim

**Comment by Patta** [comment]
hi @lochmueller ,
thanks for your feedback. Your solution works for me. :)

Thanks!

**Comment by lochmueller** [comment]
Great. I close this issue.
